openapi: 3.0.3
info:
  title: Video Comment Density Analysis API
  description: |
    API endpoint for retrieving aggregated comment density data for time-series visualization.
    Supports preset time ranges (3/7/14/30 days after publication) and custom date ranges.
    All timestamps are returned in Asia/Taipei timezone (GMT+8).
  version: 1.0.0
  contact:
    name: DISINFO_SCANNER Development Team

servers:
  - url: http://localhost:8000/api
    description: Local development server
  - url: https://urtubeapi.analysis.tw/api
    description: Production server

tags:
  - name: Video Analysis
    description: Comment density analysis endpoints

paths:
  /videos/{videoId}/comment-density:
    get:
      summary: Get complete comment density datasets for a video (optimized)
      description: |
        **OPTIMIZED DESIGN**: Returns TWO complete datasets in a single response:
        1. **Hourly data**: First 14 days after publication (up to 336 data points)
        2. **Daily data**: From publication to current date (variable data points)

        **Client-side filtering**: Frontend filters cached data based on user selection (3/7/14/30 days or custom range).
        No additional API calls needed when user switches time ranges.

        **Performance benefits**:
        - Initial load: ~1-1.5 seconds (2 database queries)
        - Subsequent range switches: 0ms (client-side filtering, no API calls)
        - Database load: 2 queries total (vs N queries in traditional design)
        - Data size: ~5-10 KB JSON (336 hourly + ~100 daily points)

        **Time granularity** (automatic):
        - Hourly data: 1-hour buckets for first 14 days
        - Daily data: 1-day buckets from publication to current date

        All timestamps are converted to Asia/Taipei timezone (GMT+8) before being returned.

        **Error handling**: Returns technical error details including trace ID, SQL query (if database error), and parameters for debugging (per FR-017).
      operationId: getCommentDensity
      tags:
        - Video Analysis
      parameters:
        - name: videoId
          in: path
          required: true
          description: YouTube video identifier
          schema:
            type: string
            example: "abc123xyz"

      responses:
        '200':
          description: Successful response with complete hourly and daily datasets
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommentDensityResponse'
              examples:
                complete_datasets:
                  summary: Complete response with both hourly and daily data (optimized)
                  value:
                    video_id: "abc123xyz"
                    video_title: "Sample Video Title"
                    video_published_at: "2025-10-10T15:00:00+08:00"

                    hourly_data:
                      range:
                        start: "2025-10-10T15:00:00+08:00"
                        end: "2025-10-24T15:00:00+08:00"
                        total_hours: 336
                      data:
                        - timestamp: "2025-10-10T15:00:00+08:00"
                          display_time: "2025-10-10 15:00 (GMT+8)"
                          count: 45
                          bucket_size: "hour"
                        - timestamp: "2025-10-10T16:00:00+08:00"
                          display_time: "2025-10-10 16:00 (GMT+8)"
                          count: 23
                          bucket_size: "hour"
                        - timestamp: "2025-10-10T17:00:00+08:00"
                          display_time: "2025-10-10 17:00 (GMT+8)"
                          count: 0
                          bucket_size: "hour"
                        # ... 333 more hourly data points (total 336)

                    daily_data:
                      range:
                        start: "2025-10-10T00:00:00+08:00"
                        end: "2025-11-19T00:00:00+08:00"
                        total_days: 40
                      data:
                        - timestamp: "2025-10-10T00:00:00+08:00"
                          display_time: "2025-10-10 00:00 (GMT+8)"
                          count: 320
                          bucket_size: "day"
                        - timestamp: "2025-10-11T00:00:00+08:00"
                          display_time: "2025-10-11 00:00 (GMT+8)"
                          count: 187
                          bucket_size: "day"
                        - timestamp: "2025-10-12T00:00:00+08:00"
                          display_time: "2025-10-12 00:00 (GMT+8)"
                          count: 0
                          bucket_size: "day"
                        # ... 37 more daily data points (total 40)

                    metadata:
                      query_time_ms: 1284
                      hourly_data_points: 336
                      daily_data_points: 40
                      trace_id: "550e8400-e29b-41d4-a716-446655440000"

        '400':
          description: Validation error - Invalid video ID (unlikely with optimized design)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error:
                  type: "ValidationException"
                  message: "The video_id field must be a valid string."
                  details:
                    trace_id: "772fa622-g40d-63f6-c938-668877662222"
                    timestamp: "2025-11-19T15:30:45+08:00"
                    parameters:
                      video_id: null

        '404':
          description: Video not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error:
                  type: "VideoNotFoundException"
                  message: "Video with ID 'invalid123' not found in database."
                  details:
                    trace_id: "883gb733-h51e-74g7-d049-779988773333"
                    timestamp: "2025-11-19T15:31:12+08:00"

        '500':
          description: Database query failure or internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error:
                  type: "DatabaseQueryException"
                  message: "Database query failed: Connection timeout after 30 seconds"
                  details:
                    trace_id: "550e8400-e29b-41d4-a716-446655440000"
                    sql: "SELECT DATE_FORMAT(CONVERT_TZ(published_at, '+00:00', '+08:00'), '%Y-%m-%d %H:00:00') as time_bucket, COUNT(*) as comment_count FROM comments WHERE video_id = ? AND published_at >= ? AND published_at <= ? GROUP BY time_bucket ORDER BY time_bucket ASC"
                    parameters:
                      video_id: "abc123xyz"
                      start_date: "2025-11-15 10:00:00"
                      end_date: "2025-11-18 10:00:00"
                    timestamp: "2025-11-19T15:30:45+08:00"

components:
  schemas:
    CommentDensityResponse:
      type: object
      description: Optimized response containing both hourly and daily complete datasets for client-side filtering
      required:
        - video_id
        - video_title
        - video_published_at
        - hourly_data
        - daily_data
        - metadata
      properties:
        video_id:
          type: string
          description: YouTube video identifier
          example: "abc123xyz"

        video_title:
          type: string
          description: Video title for context
          example: "Sample Video Title"

        video_published_at:
          type: string
          format: date-time
          description: Video publication timestamp in Asia/Taipei timezone (GMT+8)
          example: "2025-10-10T15:00:00+08:00"

        hourly_data:
          type: object
          description: Complete hourly dataset for first 14 days after publication
          required:
            - range
            - data
          properties:
            range:
              type: object
              description: Time range covered by hourly dataset
              required:
                - start
                - end
                - total_hours
              properties:
                start:
                  type: string
                  format: date-time
                  description: Video publication time in Asia/Taipei timezone (GMT+8)
                  example: "2025-10-10T15:00:00+08:00"

                end:
                  type: string
                  format: date-time
                  description: 14 days after publication OR current time (whichever is earlier) in GMT+8
                  example: "2025-10-24T15:00:00+08:00"

                total_hours:
                  type: integer
                  description: Number of hours in this range (up to 336)
                  example: 336
                  minimum: 1
                  maximum: 336

            data:
              type: array
              description: Dense hourly time-series (includes zero-count buckets for missing periods)
              items:
                $ref: '#/components/schemas/CommentDensityDataPoint'
              minItems: 1
              maxItems: 336

        daily_data:
          type: object
          description: Complete daily dataset from publication to current date
          required:
            - range
            - data
          properties:
            range:
              type: object
              description: Time range covered by daily dataset
              required:
                - start
                - end
                - total_days
              properties:
                start:
                  type: string
                  format: date-time
                  description: Video publication date (start of day) in Asia/Taipei timezone (GMT+8)
                  example: "2025-10-10T00:00:00+08:00"

                end:
                  type: string
                  format: date-time
                  description: Current date (start of day) in Asia/Taipei timezone (GMT+8)
                  example: "2025-11-19T00:00:00+08:00"

                total_days:
                  type: integer
                  description: Number of days in this range (depends on video age)
                  example: 40
                  minimum: 1

            data:
              type: array
              description: Dense daily time-series (includes zero-count buckets for missing periods)
              items:
                $ref: '#/components/schemas/CommentDensityDataPoint'
              minItems: 1

        metadata:
          type: object
          description: Performance and debugging information
          required:
            - query_time_ms
            - hourly_data_points
            - daily_data_points
            - trace_id
          properties:
            query_time_ms:
              type: integer
              description: Total database query execution time in milliseconds (both queries combined)
              example: 1284
              minimum: 0

            hourly_data_points:
              type: integer
              description: Number of hourly buckets returned
              example: 336
              minimum: 0
              maximum: 336

            daily_data_points:
              type: integer
              description: Number of daily buckets returned
              example: 40
              minimum: 0

            trace_id:
              type: string
              format: uuid
              description: Unique identifier for this request (links to server logs)
              example: "550e8400-e29b-41d4-a716-446655440000"

    CommentDensityDataPoint:
      type: object
      required:
        - timestamp
        - display_time
        - count
        - bucket_size
      properties:
        timestamp:
          type: string
          format: date-time
          description: Time bucket start in Asia/Taipei timezone (GMT+8), ISO 8601 format
          example: "2025-11-15T14:00:00+08:00"

        display_time:
          type: string
          description: Human-readable time with timezone label for UI display
          example: "2025-11-15 14:00 (GMT+8)"

        count:
          type: integer
          description: Number of comments in this time bucket (0 if no comments)
          example: 127
          minimum: 0

        bucket_size:
          type: string
          enum: [hour, day]
          description: Size of this time bucket
          example: "hour"

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: object
          required:
            - type
            - message
          properties:
            type:
              type: string
              description: Error category for client-side handling
              enum:
                - ValidationException
                - VideoNotFoundException
                - DatabaseQueryException
                - TimeoutException
              example: "DatabaseQueryException"

            message:
              type: string
              description: Human-readable error message
              example: "Database query failed: Connection timeout after 30 seconds"

            details:
              type: object
              description: Technical debugging information (per FR-017 - display technical errors)
              properties:
                trace_id:
                  type: string
                  format: uuid
                  description: Links to server logs for debugging
                  example: "550e8400-e29b-41d4-a716-446655440000"

                sql:
                  type: string
                  description: Failed SQL query (included if database error)
                  example: "SELECT DATE_FORMAT(...) FROM comments WHERE ..."

                parameters:
                  type: object
                  description: Query parameters that caused failure
                  additionalProperties: true
                  example:
                    video_id: "abc123xyz"
                    start_date: "2025-11-15 10:00:00"
                    end_date: "2025-11-18 10:00:00"

                timestamp:
                  type: string
                  format: date-time
                  description: When the error occurred (Asia/Taipei timezone)
                  example: "2025-11-19T15:30:45+08:00"
