openapi: 3.0.3
info:
  title: Video Incremental Update - Import API
  version: 1.0.0
  description: |
    API endpoint for executing incremental comment import.
    Fetches all new comments (up to 500 per request) and persists them to the database,
    then updates the video's comment_count and updated_at fields.

servers:
  - url: http://localhost:8000/api
    description: Local development server

paths:
  /video-update/import:
    post:
      summary: Execute incremental comment import
      description: |
        Import all new comments for a video (up to 500-comment limit per request).
        - Queries last comment timestamp from database
        - Calls YouTube API with publishedAfter filter
        - Inserts comments using idempotent pattern (firstOrCreate)
        - Updates video.comment_count and video.updated_at
        - Returns import result with remaining count if limit exceeded
      operationId: executeIncrementalImport
      tags:
        - Video Update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - video_id
              properties:
                video_id:
                  type: string
                  description: YouTube video ID (11 characters)
                  example: "dQw4w9WgXcQ"
                  maxLength: 11
      responses:
        '200':
          description: Import completed successfully (all comments imported)
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - data
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    required:
                      - video_id
                      - imported_count
                      - total_available
                      - remaining
                      - has_more
                      - updated_comment_count
                      - message
                    properties:
                      video_id:
                        type: string
                        example: "dQw4w9WgXcQ"
                      imported_count:
                        type: integer
                        description: Number of comments actually imported in this request
                        example: 42
                      total_available:
                        type: integer
                        description: Total number of new comments found (before limit applied)
                        example: 42
                      remaining:
                        type: integer
                        description: Number of comments still available for import (0 if all imported)
                        example: 0
                      has_more:
                        type: boolean
                        description: True if more comments remain due to 500-limit
                        example: false
                      updated_comment_count:
                        type: integer
                        description: Total comment count for video after import
                        example: 542
                      message:
                        type: string
                        description: User-friendly success message in Traditional Chinese
                        example: "成功導入 42 則留言"
        '200 - Partial Import':
          description: Import completed successfully (partial - 500 limit reached)
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - data
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    required:
                      - video_id
                      - imported_count
                      - total_available
                      - remaining
                      - has_more
                      - updated_comment_count
                      - message
                    properties:
                      video_id:
                        type: string
                        example: "dQw4w9WgXcQ"
                      imported_count:
                        type: integer
                        description: Exactly 500 (limit enforced)
                        example: 500
                      total_available:
                        type: integer
                        description: Total new comments found
                        example: 1200
                      remaining:
                        type: integer
                        description: Comments still available for next import
                        example: 700
                      has_more:
                        type: boolean
                        example: true
                      updated_comment_count:
                        type: integer
                        example: 1500
                      message:
                        type: string
                        example: "成功導入 500 則留言。還有 700 則新留言可用，請再次點擊更新按鈕繼續導入。"
        '400':
          description: Bad request (invalid video_id, video not found, etc.)
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - error
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Video not found in database"
        '404':
          description: Video deleted from YouTube (still exists in database)
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - error
                  - data
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Video not found on YouTube (may have been deleted)"
                  data:
                    type: object
                    properties:
                      video_id:
                        type: string
                        example: "dQw4w9WgXcQ"
                      suggestion:
                        type: string
                        example: "Consider removing this video from the database"
        '429':
          description: YouTube API quota exceeded
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - error
                  - data
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "YouTube API quota exceeded"
                  data:
                    type: object
                    properties:
                      retry_after:
                        type: string
                        format: date-time
                        description: Estimated time when quota resets
                        example: "2025-11-19 00:00:00"
        '500':
          description: Internal server error (database error, YouTube API failure, etc.)
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - error
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Failed to persist comments to database"

components:
  schemas: {}
