openapi: 3.0.3
info:
  title: Video Incremental Update - Preview API
  version: 1.0.0
  description: |
    API endpoint for previewing new comments available for incremental import.
    Returns the first 5 new comments (chronological order) and total count without persisting any data.

servers:
  - url: http://localhost:8000/api
    description: Local development server

paths:
  /video-update/preview:
    post:
      summary: Preview new comments for incremental update
      description: |
        Query the database for the last comment timestamp of a video,
        call YouTube API to fetch comments published after that timestamp,
        and return preview data (first 5 comments + total count) without importing.
      operationId: previewIncrementalUpdate
      tags:
        - Video Update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - video_id
              properties:
                video_id:
                  type: string
                  description: YouTube video ID (11 characters)
                  example: "dQw4w9WgXcQ"
                  maxLength: 11
                video_title:
                  type: string
                  description: Video title (optional, for display purposes)
                  example: "示例影片標題"
                  maxLength: 500
      responses:
        '200':
          description: Preview data retrieved successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - data
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    required:
                      - video_id
                      - video_title
                      - last_comment_time
                      - new_comment_count
                      - preview_comments
                      - has_more
                      - import_limit
                    properties:
                      video_id:
                        type: string
                        example: "dQw4w9WgXcQ"
                      video_title:
                        type: string
                        example: "示例影片標題"
                      last_comment_time:
                        type: string
                        format: date-time
                        description: Timestamp of the last comment in database (YYYY-MM-DD HH:MM:SS)
                        example: "2025-11-05 15:00:00"
                      new_comment_count:
                        type: integer
                        description: Total number of new comments available
                        example: 42
                      preview_comments:
                        type: array
                        description: First 5 new comments in chronological order (oldest to newest)
                        maxItems: 5
                        items:
                          type: object
                          required:
                            - comment_id
                            - author_channel_id
                            - text
                            - like_count
                            - published_at
                            - parent_comment_id
                          properties:
                            comment_id:
                              type: string
                              example: "UgxKREWJwNDMyNzQyODN4AaABAg"
                            author_channel_id:
                              type: string
                              nullable: true
                              example: "UCuAXFkgsw1L7xaCfnd5JJOw"
                            text:
                              type: string
                              description: Comment content (may be truncated to 150 chars in UI)
                              example: "這是一則示例留言內容"
                            like_count:
                              type: integer
                              minimum: 0
                              example: 5
                            published_at:
                              type: string
                              format: date-time
                              description: Comment publication timestamp (YYYY-MM-DD HH:MM:SS)
                              example: "2025-11-05 16:00:00"
                            parent_comment_id:
                              type: string
                              nullable: true
                              description: Parent comment ID if this is a reply
                              example: null
                      has_more:
                        type: boolean
                        description: True if new_comment_count > 500 (partial import will occur)
                        example: false
                      import_limit:
                        type: integer
                        description: Maximum comments per import operation
                        example: 500
        '200 - No New Comments':
          description: No new comments found (not an error, but no data to import)
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - error
                  - data
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "No new comments found"
                  data:
                    type: object
                    required:
                      - video_id
                      - last_comment_time
                      - new_comment_count
                    properties:
                      video_id:
                        type: string
                        example: "dQw4w9WgXcQ"
                      last_comment_time:
                        type: string
                        format: date-time
                        example: "2025-11-05 15:00:00"
                      new_comment_count:
                        type: integer
                        example: 0
        '400':
          description: Bad request (invalid video_id, video not found, etc.)
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - error
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Video not found in database"
        '429':
          description: YouTube API quota exceeded
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - error
                  - data
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "YouTube API quota exceeded"
                  data:
                    type: object
                    properties:
                      retry_after:
                        type: string
                        format: date-time
                        description: Estimated time when quota resets
                        example: "2025-11-19 00:00:00"
        '500':
          description: Internal server error (YouTube API failure, database error, etc.)
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - error
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Failed to fetch comments from YouTube API"

components:
  schemas: {}
